# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/12644/Desktop/cpu_pipeline_suspend/cpu_pipeline_suspend.srcs/sources_1/ip/cpu_clk/cpu_clk.xci
# IP: The module: 'cpu_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/12644/Desktop/cpu_pipeline_suspend/cpu_pipeline_suspend.srcs/sources_1/ip/cpu_clk/cpu_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/12644/Desktop/cpu_pipeline_suspend/cpu_pipeline_suspend.srcs/sources_1/ip/cpu_clk/cpu_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/12644/Desktop/cpu_pipeline_suspend/cpu_pipeline_suspend.srcs/sources_1/ip/cpu_clk/cpu_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/12644/Desktop/cpu_pipeline_suspend/cpu_pipeline_suspend.srcs/sources_1/ip/cpu_clk/cpu_clk.xci
# IP: The module: 'cpu_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/12644/Desktop/cpu_pipeline_suspend/cpu_pipeline_suspend.srcs/sources_1/ip/cpu_clk/cpu_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/12644/Desktop/cpu_pipeline_suspend/cpu_pipeline_suspend.srcs/sources_1/ip/cpu_clk/cpu_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/12644/Desktop/cpu_pipeline_suspend/cpu_pipeline_suspend.srcs/sources_1/ip/cpu_clk/cpu_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
